name: Test
on:
  push:
    paths:
      - '**.cr'
      - '.github/workflows/test.yml'
      - shard.latest.yml
  pull_request:
    branches: [master]
    paths:
      - '**.cr'
      - '.github/workflows/test.yml'
      - shard.latest.yml
  schedule:
    - cron: '0 6 * * 6'
jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        crystal: [latest]
        shard_file: [shard.latest.yml]
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install shards
        run: shards install
        env:
          SHARDS_OVERRIDE: ${{ matrix.shard_file }}
      - name: Lint code
        run: ./bin/ameba
  specs:
    strategy:
      fail-fast: false
      matrix:
        crystal: ['1.0.0']
        experimental: [false]
        shard_file: [shard.yml]
        include:
          - crystal: latest
            experimental: false
            shard_file: shard.latest.yml
          - crystal: nightly
            experimental: true
            shard_file: shard.edge.yml
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Cache shards
        uses: actions/cache@v4
        with:
          path: ~/.cache/shards
          key: ${{ runner.os }}-shards-${{ hashFiles('shard.yml') }}
          restore-keys: ${{ runner.os }}-shards-
      - name: Install shards
        run: shards update
        env:
          SHARDS_OVERRIDE: ${{ matrix.shard_file }}
      - name: Install Redis
        run: |
          sudo apt update
          sudo apt -y install redis
      - name: Start Redis
        run: sudo systemctl start redis
      - name: Run tests
        env:
          REDIS_URL: redis://localhost:6379/0
        run: crystal spec --error-on-warnings -Dpreview_mt
